### PR TITLE
Minimal changes to limit width of HTML doc page

### PR DESCRIPTION
**Pull request by giacomofiorin**
Not urgent, but needs a look.  I pushed already the accompanying changes in the website repo.

### CODE REVIEW

**Comment by giacomofiorin** [comment]
FYI I pushed the output of this change to the webpage repository, see e.g. https://colvars.github.io/colvars-refman-vmd/colvars-refman-vmd.html.  If it works, I'm inclined to just merge this in.

**Comment by jhenin** [comment]
Not sure what guidelines to follow, but that seems a little on the narrow side to me...

Side note, the graphic in fig 1 is missing.

**Comment by giacomofiorin** [comment]
@jhenin I added a simple conditional style for screen size, which makes it look OK on my phone.

As for the high-res screens showing the column to narrow, a hotkey like `Ctrl-+` or similar is supported by nearly all browsers.

**Comment by jhenin** [comment]
New layout looks good to me.

**Pull request merged**
