### PR TITLE
Support Lepton in GROMACS build

### PR DESCRIPTION
**Pull request by giacomofiorin**
This PR adds support for patching Lepton into the GROMACS build system and runtime.

A working code is at:
https://github.com/Colvars/gromacs/tree/release-2021-colvars-lepton
and will be converted into patches for this repository before merging.

### CODE REVIEW

**Comment by giacomofiorin** [comment]
Also TODO: port the change to GROMACS 2020, or drop it from the workflow.

**Comment by giacomofiorin** [comment]
@jhenin @HubLot I'm pretty much done with adding Lepton on a GROMACS tree. You can find a working branch here:
https://github.com/Colvars/gromacs/tree/release-2021-colvars-lepton
It builds and links correctly on all OSs. If you want to test using Lepton with the pull code, feel free to use it as basis; you would probably need a small change to `src/gromacs/CMakeLists.txt`:
```
target_include_directories(libgromacs PRIVATE ${PROJECT_SOURCE_DIR}/src/external/lepton/include)
```
Given that converting GROMACS-side changes into patches in the Colvars repository, I'd wait to do so only at the end, after any further changes that you think may be needed.

**Comment by HubLot** [comment]
Looks good to me!
I retrieve the branch and test the update, compilation and the `000_customfunction_harmonic-fixed` test. All working

**Comment by giacomofiorin** [comment]
FYI for maintainability purposes I put the CMake stuff for Colvars and Lepton in separate files, which are included by GROMACS' CMakeLists.txt. So now the patch for the latter is very minimal, and we have all our CMake build instructions in simple files, which are the same for all GROMACS versions.

If the tests pass I'll merge. Too bad that I can't test the Windows and macOS builds at the moment due to changes in standard GROMACS 2021, which somehow their CI didn't catch :-/ Hopefully they'll fix those soon.

**Comment by giacomofiorin** [comment]
Correction: the build errors are currently in GROMACS *master*, but our patched branches and their ancestors are okay.

**Pull request merged**
