### PR TITLE
Ebmeta free doc

### PR DESCRIPTION
**Pull request by fabsugar**

### CODE REVIEW

**Comment by fabsugar** [comment]
Note that I also updated the general metadynamics documentation, introducing some more information on how to get a better estimate of the free energy form the time average of the instantaneous profiles.

**Comment by giacomofiorin** [comment]
@jhenin See if the discussion of PMF files from TI-based methods in the multicolumn format section looks OK to you as well.
I'm going to do some minor changes to the `ebMeta` section but I'm otherwise good to go.

**Comment by fabsugar** [comment]
Hi Giacomo,
sounds good, I'll set up a default threshold (that can be optionally
changed) in the next few days and do a commit.
Fab

**Comment by jhenin** [comment]
I just replaced grid "bins" with grid points because bins refer specifically to histograms or local averages.

Looks very good otherwise.

**Pull request merged**
