### PR TITLE
[Draft] add support for GROMACS 2022

### PR DESCRIPTION
**Pull request by HubLot**
Hi,

Here a PR to add support of GROMACS 2022 (better late than never).
I add to modify the patch script because the version number is now in the global CMakeLists.txt.

Issue: I'm not able to compile on the GROMACS 2022 tree. I have `include` errors from the proxy file:
```
gromacs-2022.4_test-colvars/src/external/colvars/colvarproxy_gromacs.cpp:8:10: fatal error: gromacs/mdtypes/inputrec.h: Aucun fichier ou dossier de ce type
 #include "gromacs/mdtypes/inputrec.h"
```

I suspect it's due to the move of Colvars in the `external` folder and  their new CMake modifications (related to this global issue (https://gitlab.com/gromacs/gromacs/-/issues/3288)). 
I tried to find a solution by adapting the CMake files but without success (but I'm really a newbie with Cmake).
Do you have a clue to solve this?

### CODE REVIEW

**Comment by HubLot** [comment]
A proper solution to the issue is to separate the Colvars library files and the proxy ones.

Colvars library files remains in `src/external` and those files don't need GROMACS headers to compile (like other libraries in this library).
Colvars-GROMACS proxy files are moved back to `src/gromacs` inside `src/gromacs/applied_forces/colvarproxy` since only those require GROMACS headers.
Furthermore, it helps separate what constitute the core of Colvars and what consitute the proxy between the library and the engine.

This what is done in the last commit (3392926)

**Comment by HubLot** [comment]
Summary of the tests launched:
  - library tests: all passed
  - interface tests:
       - serial: segfault due to LINCS (need to investigate)
       - MPI: passed with 1e-5 precision
       - MPI_multi-sim: passed from 1e-3 to 1e-5 precision

**Comment by giacomofiorin** [comment]
@HubLot Separating out the library files from the GROMACS interface code makes sense in general. I only put them in the same place to be easier to maintain patched worktrees, but clearly that's less of a concern than being able to build! :-) 

For the tests, having them pass at 1e-5 accuracy or worse does not seem very useful. Are you open to adding instead unit tests of the Colvars interface to the CMake targets of GROMACS? It would seem to me more consistent with the expectations of most users.

**Comment by HubLot** [comment]
> @HubLot Separating out the library files from the GROMACS interface code makes sense in general. I only put them in the same place to be easier to maintain patched worktrees, but clearly that's less of a concern than being able to build! :-)

Indeed !

> For the tests, having them pass at 1e-5 accuracy or worse does not seem very useful. Are you open to adding instead unit tests of the Colvars interface to the CMake targets of GROMACS? It would seem to me more consistent with the expectations of most users.

Can you elaborate? You mean, having a folder `tests` inside `src/gromacs/applied_forces/colvarproxy` and run by GROMACS test suite?

**Comment by giacomofiorin** [comment]
> Can you elaborate? You mean, having a folder `tests` inside `src/gromacs/applied_forces/colvarproxy` and run by GROMACS test suite?

Yes, exactly. All the "interface" tests would be in the right place there, because you can follow a bit more closely any changes in the `MDModules` infrastructure, which are likely to happen both within and outside your control.

I don't know if it would be also the right place for the library tests, but we can think about it later.

Also, looking at the rest of the `applied_forces` folder, why not rename the `colvarproxy` folder as simply `colvars`? This would make it clearer what the folder contains without needing to know the name of a class internal to Colvars. A simple README could point to the location of the library in `src/external` to clarify that not everything is in there. Although many of the modules in there (`awk`, `densityfitting`, etc) are fully contained within GROMACS, `qmmm` certainly isn't.

**Comment by HubLot** [comment]
> Yes, exactly. All the "interface" tests would be in the right place there, because you can follow a bit more closely any changes in the `MDModules` infrastructure, which are likely to happen both within and outside your control.

Yes, it makes sense indeed but we won't be able to use colvars suite "as is" for running the tests, e.g spiff, Autodiff folder, reference files, etc, no?

> Also, looking at the rest of the `applied_forces` folder, why not rename the `colvarproxy` folder as simply `colvars`? This would make it clearer what the folder contains without needing to know the name of a class internal to Colvars. A simple README could point to the location of the library in `src/external` to clarify that not everything is in there. Although many of the modules in there (`awk`, `densityfitting`, etc) are fully contained within GROMACS, `qmmm` certainly isn't.

Agreed, I'll amend the PR.

**Comment by giacomofiorin** [comment]
> Yes, it makes sense indeed but we won't be able to use colvars suite "as is" for running the tests, e.g spiff, Autodiff folder, reference files, etc, no?
> 

That's right, but once you know that you have a working CMake and CTest, why would you use these other tools? 😉  They make sense to support NAMD and VMD but that's about it.

**Comment by HubLot** [comment]
Yes, I agree. 
I think it may be out of the scope of this PR though.

**Comment by giacomofiorin** [comment]
> Yes, I agree. I think it may be out of the scope of this PR though.

Yes, that should be a separate PR covering also other GROMACS releases that are currently supported. If you have a good idea where to start from, feel free to go ahead. Otherwise, I'm happy to take a look as well: it is worth at least considering running all the tests through CTest.

This PR looks okay right now. Do you have anything else that you plan to add?

**Comment by HubLot** [comment]
> > Yes, I agree. I think it may be out of the scope of this PR though.
> 
> Yes, that should be a separate PR covering also other GROMACS releases that are currently supported. If you have a good idea where to start from, feel free to go ahead. Otherwise, I'm happy to take a look as well: it is worth at least considering running all the tests through CTest.
> 
Okay I will look into it and let you know.

> This PR looks okay right now. Do you have anything else that you plan to add?

No, it's good. It may be worth squashing the PR though due to the smalls and not really informative commits.

**Comment by giacomofiorin** [comment]
> No, it's good. It may be worth squashing the PR though due to the smalls and not really informative commits.

Nah, it's only 5 commits, and some of them are actually large.

**Comment by giacomofiorin** [comment]
@HubLot Can you check the status of the CI jobs in https://github.com/Colvars/gromacs? I had a few hiccups in updating the patched branches, but after solving those I noticed some segfaults on macOS.

**Comment by HubLot** [comment]
it crash also on my Linux workstation, i'll investigate

**Pull request merged**
