### PR TITLE
Dipole angle  implementation

### PR DESCRIPTION
**Pull request by alejob**
New collective variable added, dipole_angle. This new implementation is similar to colvar "angle", but "calc_gradient" and vector "r21" have been modified. A new function "total_charge", similar to "total_mass", has been implemented. Also, a new function for atom group, "dipole", has been implemented. The parser for LAMMPS and NAMD has been modified to extract charges to be used in dipole calculation. The colvars-ref-manual has been modified.

### CODE REVIEW

**Comment by alejob** [comment]
Hello @giacomofiorin, @akohlmey  
          is there anything that a can do to help you to pull this?, maybe I can "paste" my implementation in the last commit on the "proxy" branch, in this way the pull request will only has the changes that I made, so, in this ways the review will be easier. Or maybe I can solve the "merge conflicts" on my own fork and then make a pull request.

Best regards

**Comment by giacomofiorin** [comment]
Sorry, I didn't have the chance to check if there were any merge
conflicts.  If there are, they should be resolved on your end.

On Fri, Jun 12, 2015 at 2:51 PM, Alejandro Bernardin <
notifications@github.com> wrote:

> Hello @giacomofiorin <https://github.com/giacomofiorin>, @akohlmey
> <https://github.com/akohlmey>
>
> is there anything that a can do to help you to pull this?, maybe I can
> "paste" my implementation in the last commit on the "proxy" branch, in this
> way the pull request will only has the changes that I made, so, in this
> ways the review will be easier. Or maybe I can solve the "merge conflicts"
> on my own fork and then make a pull request.
>
> Best regards
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/colvars/colvars/pull/41#issuecomment-111587562>.
>



-- 
Giacomo Fiorin
Assistant Professor of Research
Institute for Computational Molecular Science (ICMS)
College of Science and Technology, Temple University
1925 North 12th Street (035-07), Room 704D
Philadelphia, PA 19122-1801
Phone: +1-215-204-4213
http://goo.gl/Q3TBQU
http://giacomofiorin.github.io/
https://icms.cst.temple.edu/members.html

**Comment by alejob** [comment]
Hi @giacomofiorin,  I solved the merge conflicts.

**Comment by giacomofiorin** [comment]
I'll inspect your changes tomorrow.

On Tue, Jun 16, 2015 at 11:34 AM, Alejandro Bernardin <
notifications@github.com> wrote:

> Hi @giacomofiorin <https://github.com/giacomofiorin>, I solved the merge
> conflicts.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/colvars/colvars/pull/41#issuecomment-112472979>.
>



-- 
Giacomo Fiorin
Assistant Professor of Research
Institute for Computational Molecular Science (ICMS)
College of Science and Technology, Temple University
1925 North 12th Street (035-07), Room 704D
Philadelphia, PA 19122-1801
Phone: +1-215-204-4213
http://goo.gl/Q3TBQU
http://giacomofiorin.github.io/
https://icms.cst.temple.edu/members.html

**Comment by giacomofiorin** [comment]
Done and merged in.  Sorry it took such a long time, your changes were pretty clear, but the pull request ended up showing differences originating from other commits, which you inherited from the proxy branch.

Thanks for the patience, and hope to use this new variable soon!

**Comment by alejob** [comment]
Thank you Giacomo for the review!, actually, it was a very large commit to check due to the inherited changes that you mention, so I understand the time that you took.

I'll be aware of any problem/bug that my implementation could cause.

Cheers!

**Pull request merged**
