### PR TITLE
Implement reflecting b.c. for ext Lagrangian

### PR DESCRIPTION
**Pull request by jhenin**
In (quick) response to issue #328 

TODO:
- [ ] regtests
- [ ] documentation

### CODE REVIEW

**Comment by HanatoK** [comment]
The code looks OK, but I'm not sure if the reflecting boundary can help. The paper you mentioned in the issue exemplifies it by metadynamics, which is a biasing potential method filling the wells. Does it also generate correct gradients for eABF's estimators?

**Comment by jhenin** [comment]
Good question @HanatoK . I've looked at exactly that today, here are the results:

image

Incidentally this shows why I'm not a fan of applying wall potentials to the extended coordinate (the bypassExtendedLagrangian option of #299 ).

**Comment by HanatoK** [comment]
@jhenin It looks good!

**Comment by fhh2626** [comment]
Looks good for me. What's interesting is your results on ext. CV vs real CV. This is quite unexpected.

**Comment by jhenin** [comment]
@fhh2626 Note that when using the bias on the real CV, the same kind of artefact appears on the eABF PMF. So choosing the variable to apply the wall is choosing which estimator is wrong at the boundary.

**Pull request merged**
