### PR TITLE
Allow script interface to access parsing data

### PR DESCRIPTION
**Pull request by giacomofiorin**
This PR addresses several of the improvements listed in issues #168 (check them off once the PR is merged) and two small fixes.

### CODE REVIEW

**Comment by giacomofiorin** [comment]
Leaving unassigned for now until all parts of #168 are addressed.

**Comment by giacomofiorin** [comment]
I checked that the cv getconfig and cv resetindexgroups commands work, but have not added tests yet.  Ideally, tests of the Tcl scripting interface are best done in VMD.  At any rate, the priority should be a way to check the robustness of the Dashboard automatically.

**Comment by giacomofiorin** [comment]
@jhenin Assign to me if the changes look OK. For the other requests in #168, a separate PR should be best.

**Comment by jhenin** [comment]
Looks all good!

**Comment by giacomofiorin** [comment]
GitHub flagged the branch as identical to master after pushing, but the branch is merged alright.

**Pull request closed without merging**
