### PR TITLE
request

### PR DESCRIPTION
**Pull request by zwpku**
update to the latest version.

### CODE REVIEW

**Comment by zwpku** [comment]
Hi HanatoK,
    thanks for the message. Yes, I intend to do that. I planed to test my code before merging it to the official branch, but I was busy on another project. Maybe I could instead first add it to the official branch, and than continue the test afterwards.
Best,
Wei
________________________________
发件人: HanatoK ***@***.***>
发送时间: 2023年5月1日 11:00
收件人: Colvars/colvars ***@***.***>
抄送: zwpku ***@***.***>; Mention ***@***.***>
主题: Re: [Colvars/colvars] request (PR #515)


Hi @zwpku<https://github.com/zwpku>, do you still intend to merge the torchann into the Colvars official branch?

―

**Comment by HanatoK** [comment]
@zwpku Thanks! I am considering if I can modify your code to allow existing CVs as input rather than atomic coordinates. If you have any similar plan, then I will not reinvent the wheels.

**Comment by giacomofiorin** [comment]
@zwpku That's correct. The class `colvar::cartesian` is just a thin wrapper to a function that simply copies the atomic coordinates and sets them as the CV's values.

**Comment by zwpku** [comment]
@giacomofiorin Thanks. Then it is defintely a good idea to modify the code to support that.

**Comment by jhenin** [comment]
@zwpku Thank you for this contribution! I suggest opening a new draft PR, even if you consider it a bit early: that would give us a simple channel for discussing your current code.

**Comment by zwpku** [comment]
> @zwpku Thank you for this contribution! I suggest opening a new draft PR, even if you consider it a bit early: that would give us a simple channel for discussing your current code.

OK, I will try to implement this feature recently and open a draft PR afterwards.

**Pull request closed without merging**
