### PR TITLE
Allow NumPy-format output for plot_colvars_traj.py

### PR DESCRIPTION
**Pull request by giacomofiorin**
As described in the title, allows converting segments of a Colvars traj into a more efficient binary format supported by the quintessential Python numerical analysis library.

### CODE REVIEW

**Comment by giacomofiorin** [comment]
Second commit is because I encountered a syntax error using a Python interpreter from Anaconda, even though it was 3.8, i.e. a version that supports the syntax. Weird.

**Comment by HanatoK** [comment]
I would recommend using `pandas` and saving the data with `to_parquet`.

**Comment by giacomofiorin** [comment]
> I would recommend using `pandas` and saving the data with `to_parquet`.

Sure, but how about in addition to NumPy rather than instead of it? Do you want to add the code to this branch? Should be pretty quick since you already added the hooks for Pandas.

**Comment by HanatoK** [comment]
> > I would recommend using `pandas` and saving the data with `to_parquet`.
> 
> Sure, but how about in addition to NumPy rather than instead of it? Do you want to add the code to this branch? Should be pretty quick since you already added the hooks for Pandas.

That sounds good. I will submit another PR after this one is merged.

**Pull request merged**
